version: '3'

services:
  frontend:
    image: dkdeepak001/codedamn-web:dev0.0.4
    ports:
      - "3000:3000"
    networks:
      - my-network
  
  backend:
    image: dkdeepak001/codedamn:v0.0.11
    ports:
      - "3001:3001"
      - "4000:4000"
    environment:
      S3_URL: s3://deepak-replit/baseCode/react
      AWS_ACCESS_KEY_ID:  
      AWS_SECRET_ACCESS_KEY: 
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

